sqlite_parser.go: TSqlLexer.g4 TSqlParser.g4 antlr-4.13.1-complete.jar
	java -jar antlr-4.13.1-complete.jar -Dlanguage=Go TSqlLexer.g4 TSqlParser.g4

antlr-4.13.1-complete.jar:
	curl -O https://www.antlr.org/download/antlr-4.13.1-complete.jar


